name: Node.js CI

on:
  release:
    runs-on: [self-hosted]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Build Yarn and npm
        uses: linchpin/action-build-yarn-npm@master
      - run: yarn install
      - run: yarn dev -p 3001
